### PR TITLE
Adding public getters for IDs of annotations 

### PR DESCRIPTION
**Pull request by keighrim**
See weblicht/wlfxb#12 for the related issue. Also this PR is a copy of weblicht/wlfxb#14, re-opened by a request. 

=====
A new interface `Annotation` is introduced as an abstraction for all annotation classes. I tried to find as many first-order annotation objects as possible based on [weblicht/tcf-spec](https://github.com/weblicht/tcf-spec/blob/master/src/main/rnc-schema/textcorpus_0_4.rnc) and modified them to implements `Annotation` interface, **BUT** I might have missed some because of my lack of familiarity to the TCF world. Please review the changes and add more if necessary. These are interfaces (and their impls ) I edited. 

* `Constituent` -> `ConstituentStored`
* `ConstituentParse` -> `ConstituentParseStored`
* `DependencyParse` -> `DependencyParseStored`
* `DiscourseConnective` -> `DiscourseConnectiveStored`
* `GeoPoint` -> `GeoPointStored`
* `Lemma` -> `LemmaStored`
* `NamedEntity` -> `NamedEntityStored`
* `Orthform` -> `OrthformStored`
* `PosTag` -> `PosTagStored`
* `Reference` -> `ReferenceStored`
* `ReferencedEntity` -> `ReferencedEntityStored`
* `Sentence` -> `SentenceStored`
* `Token` -> `EmptyTokenStored` (`TokenStored` already has `getId()`)

### CODE REVIEW

**Comment by elahi123** [comment]
Hi Keigh,
I am talking about the your annotation interface for getter id with Wei (who is developer of wlfxb library) and Marie. I will let you know.

**Comment by elahi123** [comment]
Hi Keigh,
Thanks.
I discuss the annotation interface (you added) with Wei and Marie. Here is our suggestions:
We think it may not be a good idea to add annotation interface at the top of all layers for the following reasons:

1. The IDs of TCF of annotation layers (you mentioned above) are optional. Those can be Null. As the IDs can be Null so you probably have to generate these IDs anyway. We don't think you can rely on these internal optional IDs of TCF. 

2.I think the tokenID of token layer is the only one that may be useful for you. The Token layer already has a getter for ID method. The ID in token layer is not optional.All the layers contain tokenIDs. I think the TokenID may be useful for you.

3. For example, from LIF to TCF conversion,   we use the ID of the Life annotation layers for internal processing but those IDs are not presented in TCF file. For TCF, we generate our own IDs. I think probably similar thing can be for TCF to LIF conversion. In any case as mentioned above they are optional. 

4. Another option can be, I think may be, it is good idea to extend the TCF layers in LIF to TCF conversion project on your side (instead of changing wlfxb library). 

We can have a Skype meeting if it is not clear to you.

Thanks.

**Comment by marcverhagen** [comment]
Three comments on this. 

1. In the schema at https://github.com/weblicht/tcf-spec/blob/master/src/main/rnc-schema/textcorpus_0_4.rnc all ID attributes are marked as optional, which is probably not the right choice for token. 

2. As far as I can see lemmas IDs can also be linked to (by the synonomy layer) and therefore lemma IDs probably should also not be optional. More importantly, generating our own lemma IDs is not an option so we need access to the lemma ID.

3. Keith thought of some issue with generating ideas, but we will have to check this with him because Keigh and I do not remember what this issue is.

**Comment by ksuderman** [comment]
I think the issue I had was if we generate our own ID values then existing ID values are lost and anything that refersto those ID values is lost as well; e.g. Lemma/Synonomy.   Currently the TCF examples we have contain information that is not available through the Java API.  I think at the least we need a `getId()` method on Lemma objects, and having a `getId()` method on all objects that might have an ID value is not a bad idea.

**Comment by marcverhagen** [comment]
Ah, so the issue only arises for those identifiers that are referred to, in other cases we do not mind making up identifiers. So as long as we have getters for tokens and lemmas we are okay since other categories are never referred to.

**Comment by elahi123** [comment]
Hi, all
Many thanks for your suggestions and ideas, so the bottom line (so far I understand) is as Marc said 'So as long as we have getters for tokens and lemmas we are okay since other categories are never referred to.' I will discuss and test and let you know the update.

**Comment by elahi123** [comment]
Hi, Thanks for the suggestions.
I am adding the getter for ID for token and lemma layer.For time being, I suppose that is enough for our converters.

Later,the getter ID (and other public methods) are new use cases for our library. We will provide an extended version for similar purpose.

**Comment by keighrim** [comment]
Sounds good. I'll close this PR (and related issues).

**Pull request closed without merging**
